plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'db/data/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'lib/templates/**/*'

# Adjust these based on your preferences
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'app/services/**/*'

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'app/services/**/*'
    - 'app/datatables/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'spec/**/*'

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Rails/I18nLocaleTexts:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - 'app/datatables/**/*'

Naming/VariableNumber:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Security/Eval:
  Exclude:
    - 'app/serializers/**/*'

Lint/EmptyBlock:
  Exclude:
    - 'app/helpers/**/*'
    - 'app/datatables/**/*'
    - 'lib/tasks/**/*'
