default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: password_manager_development

test:
  <<: *default
  database: password_manager_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
