# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 809caa38f23f878b1295f68b695351a50bb7c9e0bf2277c236b1387dd6d0c5800fe0c5d278a86bbcd31e65f71d68bb02c8f15eef342bb1e0cbdce035d856d4d3

test:
  secret_key_base: c9edf187ebcae34df130b4f7ed9dbdf43bfc2e9a4cb2687d052aa76e0f2b2cf73a8de97a09c4bf387cd292341a289f800c5aba7345876e69c436e80d3078d54c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
